junit:
  stage: test
  script:
    - cd team2fitness
    - mvn -B clean test
generate_artifacts:
  stage: deploy
  script:
    - cd team2fitness
    - mvn -B clean package
  artifacts:
    paths:
    - team2fitness/target/team2*.jar
